### ISSUE TITLE
Link to PATh16 dataset

### ISSUE THREAD

**Issue by Areeb2735** [GiantJun/CL_Pytorch#1]
Hi,
Great code.

Can you please provide the link to the path16 dataset? The link mentioned in the paper needs to be fixed. 

Thanks

**Comment by GiantJun** [comment]
Thanks for the heads up!

The link to the path16 dataset is https://drive.google.com/drive/folders/1LMHgawD83Z5EmYN6wtLVIibZNrAZglZt?usp=sharing .
